language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis ci 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    -  'HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일 알람
notifications:
  email:
    recipients:
      - y718j@naver.com