language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis ci 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    -  'HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r blog-exercise *
  - mkdir -p deploy
  - mv blog-exercise.zip deploy/blog-exercise.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: yangpring-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private

    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: :$AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yangpring-build
    key: blog-exercise.zip
    bundle_type: zip
    application: blog-service
    deployment_group: yangpring-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일 알람
notifications:
  email:
    recipients:
      - y718j@ajou.ac.kr